web:
  build: .
  volumes:
   - .:/code
  links:
   - redis
  expose:
   - "8080"
  environment:
   - VIRTUAL_HOST=teste.docker
redis:
  image: redis:3.2-alpine
lb:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - 80:80
